# Generated by Django 4.2 on 2023-05-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
