# Generated by Django 4.2 on 2023-05-10 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
