# Generated by Django 4.2 on 2023-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_creator_post_user_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
